---
- name: Add WireGuard repository
  apt_repository:
    repo: "{{ wireguard_repo_url }}"
    state: present
    update_cache: yes
  when: wireguard_repo_url
  tags:
    - wg-install

- name: Install required packages
  package:
    name: "{{ wireguard_distro_packages }}"
    state: present
  tags:
    - wg-install
