---

# - debug: msg="{{ item.WireGuardPeer | json_query('[?"AllowedIPs"].AllowedIPs') }}"
#   loop: "{{ peers }}"

# - debug: msg="{{ item.WireGuardPeer | json_query('[?"PublicKey"].PublicKey') }}"
#   loop: "{{ peers }}"

- name: Create clients configs
  template:
    src: "clients.conf.j2"
    dest: "{{ wireguard_clients_dir }}/{{ item | to_uuid }}.conf"
    mode: 0644
  vars:
    server_public_key: "{{ _pubkey_value['content'] | b64decode }}"
    preshared_key: "{{ _pskkey_value['content'] | b64decode }}"
  loop: "{{ peers | list }}"
  notify:
    - restart systemd-networkd

- name: Copy client configs
  shell: cp -u $(grep -iRl '{{ item.publickey }}' {{ wireguard_clients_dir }}/) /tmp/{{ item.name }}.conf
  loop: "{{ wireguard_peers | list }}"
  when: wireguard_download_clients | bool

- name: Download client configs
  fetch:
    src: /tmp/{{ item.name }}.conf
    dest: "{{ wireguard_clients_download_dir }}"
  loop: "{{ wireguard_peers | list }}"
  when: wireguard_download_clients | bool
